version: "3.8"

services:
  jmemo:
    build:
      context: ./jmemo
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
